apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-api-ingress
  namespace: 25RP18224-nzayisenga
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: employee.25rp18224-nzayisenga.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: employee-api
            port:
              number: 80
